---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ncert-manager.io/cluster-issuer: "http01-clusterissuer"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - "prometheus.best-store-dumpling.ru"
      secretName: prometheus-secret
  rules:
  - host: "prometheus.best-store-dumpling.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus
            port:
              number: 9090