--- 
apiVersion: v1 
kind: ServiceAccount 
metadata: 
  name: prometheus 
  namespace: momo-store 
  labels: 
    app.kubernetes.io/managed-by: Helm 
  annotations: 
    meta.helm.sh/release-name: prometheus 
    meta.helm.sh/release-namespace: momo-store 
 
--- 
apiVersion: rbac.authorization.k8s.io/v1 
kind: Role 
metadata: 
  name: prometheus 
  namespace: momo-store 
  labels: 
    app.kubernetes.io/managed-by: Helm 
  annotations: 
    meta.helm.sh/release-name: prometheus 
    meta.helm.sh/release-namespace: momo-store 
rules: 
  - apiGroups: [""] 
    resources: ["pods", "nodes", "nodes/proxy", "services", "endpoints", "events"] 
    verbs: ["get", "list", "watch"] 
 
--- 
apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding 
metadata: 
  name: prometheus 
  namespace: momo-store 
  labels: 
    app.kubernetes.io/managed-by: Helm 
  annotations: 
    meta.helm.sh/release-name: prometheus 
    meta.helm.sh/release-namespace: momo-store 
subjects: 
  - kind: ServiceAccount 
    name: prometheus 
    namespace: momo-store 
roleRef: 
  kind: Role 
  name: prometheus 
  apiGroup: rbac.authorization.k8s.io
