apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 9090
      protocol: TCP
  selector:
    app: prometheus
  sessionAffinity: None
  type: ClusterIP
