version: '3'
services:
  backend:
    image: backend:latest
    ports:
      - "8081:8081"
    networks:
      - pelmen
  frontend:
    image: frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - pelmen
networks:
  pelmen:
